workspace 'UtilityLib'

xcodeproj 'MyTestDemo/MyTestDemo.xcodeproj'
xcodeproj 'MyUtilityLib/MyUtilityLib.xcodeproj'

target :MyTestDemo do
platform :ios, '6.0'
pod 'AFNetworking', '~> 2.1.0'
xcodeproj 'MyTestDemo/MyTestDemo.xcodeproj'
end

target :MyUtilityLib do
platform :ios, '6.0'
pod 'AFNetworking', '~> 2.1.0'
xcodeproj 'MyUtilityLib/MyUtilityLib.xcodeproj'
end
